### ISSUE TITLE
Problem with Roboware for ubuntu 20

### ISSUE THREAD

**Issue by TrabelsiHoussem** [sgzuccaro/RoboWare#1]
i got a problem after the installation of roboware studio, when i try to run it  the application has closed unexpectedly

**Comment by JackMi-HUB** [comment]
hello! i also got this problem when i run it in ubuntu 20. have you found the solution yet?

**Comment by sgzuccaro** [comment]
Im sorry, but im pretty sure Ubuntu 16.04 is the last version supported by this IDE.
